const mockSearchData = {
    total_products: 72236,
    country: 'US',
    domain: 'www.amazon.com',
    products: [
        {
            asin: 'B0CN1QSH8Q',
            product_title:
                'SAMSUNG Galaxy A15 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Expandable Storage, Knox Security, Super Fast Charging, US Version, 2024, Blue Black',
            product_price: '$199.99',
            product_original_price: null,
            currency: 'USD',
            product_star_rating: '3.9',
            product_num_ratings: 389,
            product_url: 'https://www.amazon.com/dp/B0CN1QSH8Q',
            product_photo:
                'https://m.media-amazon.com/images/I/61s0ZzwzSCL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$199.99',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: true,
            sales_volume: '2K+ bought in past month',
            delivery:
                'FREE delivery Mon, Jun 3 Or fastest delivery Thu, May 30',
        },
        {
            asin: 'B0CSB22F9C',
            product_title:
                'Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)',
            product_price: '$136.99',
            product_original_price: '$148.07',
            currency: 'USD',
            product_star_rating: '4.1',
            product_num_ratings: 161,
            product_url: 'https://www.amazon.com/dp/B0CSB22F9C',
            product_photo:
                'https://m.media-amazon.com/images/I/51rp0nqaPoL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$136.99',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '6K+ bought in past month',
            delivery: 'FREE delivery Mon, Jun 3 Or fastest delivery Sat, Jun 1',
        },
        {
            asin: 'B0CCSZZGT7',
            product_title:
                'TracFone Motorola Moto g Play, 32GB, Black - Prepaid Smartphone (Locked)',
            product_price: '$39.88',
            product_original_price: '$49.99',
            currency: 'USD',
            product_star_rating: '4.1',
            product_num_ratings: 118,
            product_url: 'https://www.amazon.com/dp/B0CCSZZGT7',
            product_photo:
                'https://m.media-amazon.com/images/I/71pGGUaxezL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$39.88',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '2K+ bought in past month',
            delivery: 'FREE delivery Mon, Jun 3 Or fastest delivery Sat, Jun 1',
        },
        {
            asin: 'B0CSB1GX4H',
            product_title:
                'Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Yellow)',
            product_price: '$129.99',
            product_original_price: '$139.96',
            currency: 'USD',
            product_star_rating: '4.2',
            product_num_ratings: 51,
            product_url: 'https://www.amazon.com/dp/B0CSB1GX4H',
            product_photo:
                'https://m.media-amazon.com/images/I/51rK-Be8dxL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$129.99',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '1K+ bought in past month',
            delivery:
                'FREE delivery Mon, Jun 3 Only 2 left in stock - order soon.',
        },
        {
            asin: 'B092NTYZ78',
            product_title:
                'Panasonic Compact Cordless Phone with DECT 6.0, 1.6&quot; Amber LCD and Illuminated HS Keypad, Call Block, Caller ID, Multiple Display Languages - 1 Handset - KX-TGB810S (Black/Silver)',
            product_price: '$24.99',
            product_original_price: null,
            currency: 'USD',
            product_star_rating: '4.2',
            product_num_ratings: 5114,
            product_url: 'https://www.amazon.com/dp/B092NTYZ78',
            product_photo:
                'https://m.media-amazon.com/images/I/81k6vcykYYL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$24.99',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '2K+ bought in past month',
            delivery:
                'FREE delivery Mon, Jun 3 on $35 of items shipped by AmazonOr fastest delivery Sat, Jun 1',
        },
        {
            asin: 'B09SM24S8C',
            product_title:
                'Samsung Galaxy A03s Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 32GB, Long Lasting Battery, Expandable Storage, 3 Camera Lenses, Infinite Display - Black (Renewed)',
            product_price: '$69.99',
            product_original_price: '$87.14',
            currency: 'USD',
            product_star_rating: '4',
            product_num_ratings: 355,
            product_url: 'https://www.amazon.com/dp/B09SM24S8C',
            product_photo:
                'https://m.media-amazon.com/images/I/51m45B3Yy+L._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$69.99',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: false,
            climate_pledge_friendly: true,
            sales_volume: '1K+ bought in past month',
            delivery: 'FREE delivery Thu, May 30',
        },
        {
            asin: 'B07ZPJW2XH',
            product_title:
                'Apple iPhone 11, 64GB, White - Fully Unlocked (Renewed)',
            product_price: '$214.00',
            product_original_price: '$229.69',
            currency: 'USD',
            product_star_rating: '4.3',
            product_num_ratings: 50142,
            product_url: 'https://www.amazon.com/dp/B07ZPJW2XH',
            product_photo:
                'https://m.media-amazon.com/images/I/31PY10NqSLL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$214.00',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: false,
            climate_pledge_friendly: true,
            sales_volume: '500+ bought in past month',
            delivery:
                'FREE delivery Thu, May 30 Only 3 left in stock - order soon.',
        },
        {
            asin: 'B000050FZP',
            product_title:
                'AT&amp;T 210 Basic Trimline Corded Phone, No AC Power Required, Wall-Mountable, White',
            product_price: '$15.95',
            product_original_price: '$22.33',
            currency: 'USD',
            product_star_rating: '4.2',
            product_num_ratings: 19324,
            product_url: 'https://www.amazon.com/dp/B000050FZP',
            product_photo:
                'https://m.media-amazon.com/images/I/610brW3Dn7L._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$15.95',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '2K+ bought in past month',
            delivery:
                'FREE delivery Mon, Jun 3 on $35 of items shipped by AmazonOr fastest delivery Sat, Jun 1',
        },
        {
            asin: 'B0CMDPRN7M',
            product_title:
                'SAMSUNG Galaxy S24 Cell Phone, 128GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Cobalt Violet',
            product_price: null,
            product_original_price: null,
            currency: null,
            product_star_rating: '4.4',
            product_num_ratings: 1183,
            product_url: 'https://www.amazon.com/dp/B0CMDPRN7M',
            product_photo:
                'https://m.media-amazon.com/images/I/716UvwH-NvL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: null,
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: true,
            sales_volume: '100+ bought in past month',
            delivery:
                'FREE delivery Mon, Jun 3 Or fastest delivery Thu, May 30',
        },
        {
            asin: 'B086QB7WZ1',
            product_title:
                'AT&amp;T BL102-2 DECT 6.0 2-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black',
            product_price: '$46.27',
            product_original_price: '$56.95',
            currency: 'USD',
            product_star_rating: '4.3',
            product_num_ratings: 25968,
            product_url: 'https://www.amazon.com/dp/B086QB7WZ1',
            product_photo:
                'https://m.media-amazon.com/images/I/81vjTHTF9WL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$46.27',
            is_best_seller: true,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '3K+ bought in past month',
            delivery: 'FREE delivery Mon, Jun 3 Or fastest delivery Sat, Jun 1',
        },
        {
            asin: 'B0C5DFJ3CV',
            product_title:
                'Alcatel 1 (32GB) 5.0&quot; Full View Display - Removable Battery - Dual SIM GSM Unlocked US &amp; Global 4G LTE International Version - Al Aqua',
            product_price: '$35.99',
            product_original_price: '$42.99',
            currency: 'USD',
            product_star_rating: '3.6',
            product_num_ratings: 31,
            product_url: 'https://www.amazon.com/dp/B0C5DFJ3CV',
            product_photo:
                'https://m.media-amazon.com/images/I/71EpXBL9yZL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$35.99',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '300+ bought in past month',
            delivery:
                'FREE delivery Mon, Jun 3 Or fastest delivery Sat, Jun 1 Only 20 left in stock - order soon.',
        },
        {
            asin: 'B0CT6BQV81',
            product_title:
                'Moto G Power 5G | 2024 | Unlocked | Made for US 8/128GB | 50MP Camera | Midnight Blue',
            product_price: '$279.99',
            product_original_price: '$299.99',
            currency: 'USD',
            product_star_rating: '4.2',
            product_num_ratings: 1729,
            product_url: 'https://www.amazon.com/dp/B0CT6BQV81',
            product_photo:
                'https://m.media-amazon.com/images/I/61c9OZyq2yL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$279.99',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '500+ bought in past month',
            delivery:
                'FREE delivery Mon, Jun 3 Or fastest delivery Thu, May 30',
        },
        {
            asin: 'B0BLZN9NDG',
            product_title:
                'SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32GB,6.5&#x27;&#x27; GSM Unlocked,International Version-Black',
            product_price: '$87.90',
            product_original_price: '$105.00',
            currency: 'USD',
            product_star_rating: '3.7',
            product_num_ratings: 290,
            product_url: 'https://www.amazon.com/dp/B0BLZN9NDG',
            product_photo:
                'https://m.media-amazon.com/images/I/71O2YkTlq-L._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$87.90',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '1K+ bought in past month',
            delivery: 'FREE delivery Mon, Jun 3 Or fastest delivery Sat, Jun 1',
        },
        {
            asin: 'B0CHHL5R3H',
            product_title:
                'Total by Verizon TCL 30 Z, 32GB, Black - Prepaid Smartphone (Locked)',
            product_price: '$39.97',
            product_original_price: null,
            currency: 'USD',
            product_star_rating: '4.8',
            product_num_ratings: 15,
            product_url: 'https://www.amazon.com/dp/B0CHHL5R3H',
            product_photo:
                'https://m.media-amazon.com/images/I/718+xprSIBL._AC_SX444_SY639_QL65_.jpg',
            product_num_offers: 1,
            product_minimum_offer_price: '$39.97',
            is_best_seller: false,
            is_amazon_choice: false,
            is_prime: true,
            climate_pledge_friendly: false,
            sales_volume: '300+ bought in past month',
            delivery: 'FREE delivery Mon, Jun 3 Or fastest delivery Sat, Jun 1',
        },
    ],
};

export default mockSearchData;
